name: CI
on:
  pull_request:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-posters:
    name: "Build posters"
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Install LaTeX packages"
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            texlive-base \
            texlive-latex-base \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-science

      - name: "Build posters"
        run: make all

      - name: "Upload posters"
        uses: actions/upload-artifact@v2
        with:
          name: posters
          path: out/*.pdf
